# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Workflow

on:
  push:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g npm@7
    - run: npx npm@7 install
    - run: ./run.sh

  build_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/

    - run: ls -la
    - run: git config --global user.email "${{ secrets.GH_USER_EMAIL }}"
    - run: git config --global user.name "${{ secrets.GH_USER }}"

    - run: npm install -g npm@7
    - run: npm --version
    - run: npm install -g lerna
    - run: which lerna
    - run: npm install

    - name: Configure NPM
      run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
        echo '@maxjeffos:registry=https://npm.pkg.github.com' >> .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     - run: npm login --registry=https://npm.pkg.github.com --scope=@maxjeffos
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
#     - run: npm whoami
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # make git ignore the changes to .npmrc so lerna doesn't complain
    - run: git update-index --skip-worktree -- .npmrc
    - run: lerna publish minor --yes --registry=https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install ghr - for uploading GitHub artifacts
      run: |
        which go
        go version
        go get -u github.com/tcnksm/ghr
        
#     - name: Create binaries with pkg
#       run: |
#         npx pkg .
#         ls -la
