# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Workflow

on:
  push:
    branches: [ master ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g npm@7
    - run: npx npm@7 install
    - run: ./run.sh

  build_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/

    - run: ls -la
    - run: git config --global user.email "${{ secrets.GH_USER_EMAIL }}"
    - run: git config --global user.name "${{ secrets.GH_USER }}"
    - run: |
       gpg --list-keys
       gpg --list-secret-keys
       echo -e "$GPG_KEY" | gpg --import
       gpg --list-secret-keys --keyid-format LONG
       git config --global commit.gpgsign true
       git config --global gpg.program gpg2
       echo "test" | gpg2 --clearsign
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}

    - run: npm install -g npm@7
    - run: npm --version
    - run: npm install -g lerna
    - run: which lerna
    - run: npm install

    - name: Configure NPM
      run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
        echo '@maxjeffos:registry=https://npm.pkg.github.com' >> .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     - run: npm login --registry=https://npm.pkg.github.com --scope=@maxjeffos
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    # make git ignore the changes to .npmrc so lerna doesn't complain
    - run: git update-index --skip-worktree -- .npmrc
    - run: lerna publish minor --yes --registry=https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Create binaries with pkg
      run: |
        echo '' > dist/STANDALONE
        npx pkg . -t node14-alpine-x64 -o sweetcli-alpine
        npx pkg . -t node12-linux-x64 -o sweetcli-linux
        npx pkg . -t node12-macos-x64 -o sweetcli-macos
        npx pkg . -t node12-win-x64 -o sweetcli-win.exe
        # TODO: build docker release
        # TODO: sign win binary
        # TODO: shasum for win?
        shasum -a 256 sweetcli-linux > sweetcli-linux.sha256 && shasum -a 256 sweetcli-macos > sweetcli-macos.sha256 && shasum -a 256 sweetcli-alpine > sweetcli-alpine.sha256
        ls -la

    - name: Create release
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "latest_tag: ${latest_tag}"        
        gh release create $latest_tag
        gh release upload $latest_tag sweetcli-alpine sweetcli-linux sweetcli-macos sweetcli-win.exe sweetcli-linux.sha256 sweetcli-macos.sha256 sweetcli-alpine.sha256
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
